name: Linux Build

on:
  workflow_dispatch:
  push:
    branches: [ "cmake" ]
  pull_request:
    branches: [ "cmake" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libsdl2-dev cmake ninja-build

    - name: Configure CMake
      run: |
        cmake -B build \
        -G Ninja \
        -DCMAKE_BUILD_TYPE=Release \
        -S ${{ github.workspace }}

    - name: Build
      run: cmake --build build --parallel

    - name: Upload Binary
      uses: actions/upload-artifact@v4
      with:
        name: sm-linux
        path: |
          build/sm
          build/*.ini
